version: "3"
services:
  nginx-tutorial:
    container_name: nginx-tutorial
    image: nginx:alpine
    restart: always
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/tutorial.conf

  sql-server-tutorial:
    container_name: sql-server-tutorial
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    user: root
    networks:
      - tutorial-net
    ports:
      - "1433:1433"
    volumes:
      # - ./AspNetTutorial/DB:/docker-entrypoint-initdb.d
      - ${EXTERNAL_RESOURCES}/sql-server-tutorial:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=${MSSQL_PASSWORD}

  asp-net-tutorial:
    container_name: asp-net-tutorial
    image: asp-net-tutorial-5.0
    build:
      context: ./AspNetTutorial
      dockerfile: Dev.dockerfile
    restart: always
    networks:
      - tutorial-net
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sql-server-tutorial
    volumes:
      - ${EXTERNAL_RESOURCES}/asp-net-tutorial:${ASP_NET_DOCKER_EXTERNAL_RESOURCES}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASP_NET_ENVIROMENT}
      - ServerEndPoint=${ASP_NET_SERVER_END_POINT}
      - ConnectionStrings__AspNetTutorial=${CONNECTION_STRING}
      - StaticPath=${ASP_NET_DOCKER_EXTERNAL_RESOURCES}
      - SecretKey=${SECRET_KEY}

  nuxt-vue-tutorial:
    container_name: nuxt-vue-tutorial
    image: nuxt-vue-tutorial-16.0
    build: ./nuxt-vue-tutorial
    restart: always
    networks:
      - tutorial-net
    ports:
      - "3000:3000"
    depends_on:
      - asp-net-tutorial
    environment:
      - HOST=0.0.0.0
      - API_BASE_URL=${API_BASE_URL}

networks:
  tutorial-net:
    driver: bridge
